### ISSUE TITLE
Alpha build requirements

### ISSUE THREAD

**Issue by tessellates** [tessellates/Solid#7]
Let us set our goal to release an Alpha build, with achievable requirements.

###Requirements
- [ ] Refactor PieceManager. Instance creation of pieces should be incapsulated in non-static scene (unity object) class. Which supports load-in of tile sets (and does not require manual scene work) :
- [ ] Create base homogenous tile set:
- [ ] Main menu which loads all level xml files which you can select from with -- with play and edit buttons:
- [ ] Create level editor
- [ ] Create title cards for level transitions
